sonar.projectKey=SOFTSUAVE-HIRE-BE
sonar.projectName=SOFTSUAVE-HIRE-BE
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=test
sonar.language=py
sonar.python.version=3

sonar.exclusions=.venv/**,**/__pycache__/**,**/tests/**
sonar.test.inclusions=test/**

# Coverage report produced by: pytest --cov=app --cov-report=xml
sonar.python.coverage.reportPaths=coverage.xml

sonar.host.url=http://localhost:9000
sonar.token=squ_c80d1ca46e6f44959b45f340eb698d391fa9919c
